databases:
  - name: tibau-db
    plan: free
    databaseName: tibau
    user: tibau

services:
  - type: web
    name: prefeitura-tibau-do-sul
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tibau-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.production
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: WEB_CONCURRENCY
        value: "4"
